server:
  port: 1212
spring:
  application:
    name: personal-demo # 服务名
  mvc: # 需要修改MVC的匹配策略，不然会不显示接口
    path match:
      matching-strategy: ant_path_matcher
  aop:
    auto: true  #启动aop配置
#  数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
 #rabbitmq配置
  rabbitmq:
    virtual-host: /heima
    username: guest
    password: guest
    addresses: 127.0.0.1:5672

  redis:
    host: localhost #redis 服务器地址
    database: 0 #redis数据库索引(默认是0)
    port: 6379 #redis服务器连接端口
    password:  #redis服务器连接密码(默认为空)
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1ms #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    connect-timeout: 3000ms #连接超时时间(单位：毫秒)
# mybatis配置
mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: com/itself/user/mapper/*.xml
  type-aliases-package: com.itself.user.mapper.UserMapper

# 测试value注解取值
demo:
  test: 100
aaa:
  name: duJi
  age: 18





